# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/services/bookkeeping_service_grpc/structure.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5src/services/bookkeeping_service_grpc/structure.proto\"\x16\n\x05\x43heck\x12\r\n\x05\x63heck\x18\x01 \x01(\x0c\"\'\n\x08Response\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0b\n\x03tax\x18\x02 \x01(\x05\x32\x36\n\x12\x42ookkeepingService\x12 \n\tSendCheck\x12\x06.Check\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.services.bookkeeping_service_grpc.structure_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHECK']._serialized_start=57
  _globals['_CHECK']._serialized_end=79
  _globals['_RESPONSE']._serialized_start=81
  _globals['_RESPONSE']._serialized_end=120
  _globals['_BOOKKEEPINGSERVICE']._serialized_start=122
  _globals['_BOOKKEEPINGSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
